# Generated by Django 4.1 on 2023-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPrimerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
